name: Build binaries

on:
  workflow_dispatch:
    inputs:
      profile:
        default: "maxperf"
        description: "Build profile"
        type: choice
        options:
          - "release"
          - "maxperf"
          - "profiling"

permissions:
  contents: read

concurrency:
  group: build-${{ github.head_ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    permissions:
      contents: read
    uses: tempoxyz/gh-actions/.github/workflows/rust-build-binaries.yml@e54b0aa0cfa6aefaceaaf94a15233cd6278714a9
    with:
      binaries: tempo-zone
      profile: ${{ inputs.profile || 'maxperf' }}
      runs-on: depot-ubuntu-latest-16
      retention-days: 90
