name: Label PRs

on:
  pull_request:
    types: [opened]

permissions: {}

jobs:
  label:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    uses: tempoxyz/gh-actions/.github/workflows/label-prs.yml@aa3bffab06ae17963818e139302b186d1f42ec8a
