name: Label PRs

on:
  pull_request:
    types: [opened]

permissions: {}

jobs:
  label:
    permissions:
      contents: read
      issues: write
    uses: tempoxyz/gh-actions/.github/workflows/label-prs.yml@e54b0aa0cfa6aefaceaaf94a15233cd6278714a9
