name: Lint

permissions: {}

on:
  push:
    branches: [main]
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  lint:
    permissions:
      contents: read
    uses: tempoxyz/gh-actions/.github/workflows/rust-lint.yml@2ddd4a5c02d66ea0ef6d9857b20fd6c2416eb9f4
