name: Scan

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
  pull_request:
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"

permissions: {}

jobs:
  scan:
    permissions:
      actions: read
      contents: read
    uses: tempoxyz/gh-actions/.github/workflows/scan-github-actions.yml@656109a25bd988bac138f9dd510a896c5b20ab9a
