name: Scan GitHub Actions

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
  pull_request:
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"

permissions: {}

jobs:
  scan:
    permissions:
      actions: read
      contents: read
    uses: tempoxyz/gh-actions/.github/workflows/scan-github-actions.yml@522daf45baa691955122a3287df2bb2d2cef264f
