name: Scan

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
  pull_request:
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"

permissions: {}

jobs:
  scan:
    permissions:
      actions: read
      contents: read
    uses: tempoxyz/gh-actions/.github/workflows/scan-github-actions.yml@e54b0aa0cfa6aefaceaaf94a15233cd6278714a9
